/**
 * TemporalSafe bundler — zero dependencies.
 * Strips ES module `export` keywords and wraps temporalsafe.js in an IIFE,
 * then emits a Tampermonkey userscript and a plain bookmarklet bundle.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(new URL('./temporalsafe.js', import.meta.url), 'utf8');

const stripExports = (s) =>
  s.replace(/^export\s+(?=(?:default\s+)?(?:function|class|const|let|var|async))/gm, '');

const body = stripExports(src);

const userHeader = `// ==UserScript==
// @name         TemporalSafe
// @namespace    markkirby125
// @version      0.1.0
// @description  Page-level flicker and flash reducer for photosensitive and migraine users
// @match        *://*/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

`;

const userJs = `${userHeader}(() => {\n${body}\n})();\n`;
const bookmarklet = `/* TemporalSafe bookmarklet bundle — generated by build.js, do not edit. */\n(() => {\n${body}\n})();\n`;

writeFileSync(new URL('./temporalsafe.user.js', import.meta.url), userJs);
writeFileSync(new URL('./temporalsafe.bookmarklet.js', import.meta.url), bookmarklet);
console.log(`temporalsafe.user.js: ${Buffer.byteLength(userJs)} bytes`);
console.log(`temporalsafe.bookmarklet.js: ${Buffer.byteLength(bookmarklet)} bytes`);
